server:
  port: 8081
  servlet:
    context-path: /

spring:
  mail:
    host: smtp.gmail.com
    username: errandsemailalert@gmail.com
    password: 178ueee34
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true
  rabbitmq:
    host: rabbitmq
